/** @type {import('./_venera_.js')} */

class Pixiv extends ComicSource {

    // ============================================================
    //  BASIC INFO
    // ============================================================
    name = "Pixiv"
    key = "pixiv"
    version = "0.4.0"
    minAppVersion = "1.6.0"
    url = "https://cdn.jsdelivr.net/gh/theoldman-lab/venera-configs@main/pixiv.js"

    // ============================================================
    //  CONSTANTS
    // ============================================================
    static AUTH_URL      = "https://oauth.secure.pixiv.net/auth/token"
    static CLIENT_ID     = "MOBrBDS8blbauoSck0ZfDbtuzpyT"
    static CLIENT_SECRET = "lsACyCD94FhDUtGTXi3QzcFE2uU1hqtDaKeqrdwj"
    static HASH_SECRET   = "28c1fdd170a5204386cb1313c7077b34f83e4aaf4aa829ce78c231e05b0bae2c"
    static USER_AGENT    = "PixivAndroidApp/5.0.166 (Android 10.0; Pixel C)"
    static REDIRECT_URI  = "https://app-api.pixiv.net/web/v1/users/auth/pixiv/callback"
    static PKCE_CHARS    = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"

    static _pkceVerifier = ""

    get apiBase() {
        return this.loadSetting('apiHost') || 'https://app-api.pixiv.net'
    }

    // ============================================================
    //  INIT — regenerate PKCE challenge for fresh sessions
    // ============================================================

    init() {
        // PKCE already generated by IIFE in loginWithWebview.url
    }

    _regeneratePkce() {
        let chars = Pixiv.PKCE_CHARS
        let verifier = ''
        for (let i = 0; i < 128; i++) {
            verifier += chars[randomInt(0, chars.length - 1)]
        }
        Pixiv._pkceVerifier = verifier

        let hash = Convert.sha256(Convert.encodeUtf8(verifier))
        let b64 = Convert.encodeBase64(hash)
        let challenge = ''
        for (let i = 0; i < b64.length; i++) {
            let c = b64[i]
            if (c === '+') challenge += '-'
            else if (c === '/') challenge += '_'
            else if (c === '=') break
            else challenge += c
        }

        this.account.loginWithWebview.url =
            'https://app-api.pixiv.net/web/v1/login' +
            '?code_challenge=' + challenge +
            '&code_challenge_method=S256' +
            '&client=pixiv-android'
    }

    // ============================================================
    //  SIGN HEADERS
    // ============================================================

    getSignHeaders() {
        let d = new Date()
        let time = d.toISOString().replace(/\.\d+Z$/, '+00:00')
        let hash = Convert.hexEncode(
            Convert.md5(Convert.encodeUtf8(time + Pixiv.HASH_SECRET))
        )
        return {
            'X-Client-Time':    time,
            'X-Client-Hash':    hash,
            'User-Agent':       Pixiv.USER_AGENT,
            'App-OS':           'Android',
            'App-OS-Version':   'Android 10.0',
            'App-Version':      '5.0.166',
            'Accept-Language':  'zh-cn'
        }
    }

    getApiHeaders() {
        let token = this.loadData('access_token')
        if (!token) return null
        let h = this.getSignHeaders()
        h['Authorization'] = 'Bearer ' + token
        h['Host'] = 'app-api.pixiv.net'
        return h
    }

    getPostHeaders() {
        let h = this.getApiHeaders()
        if (!h) return null
        h['Content-Type'] = 'application/x-www-form-urlencoded'
        return h
    }

    // ============================================================
    //  TOKEN EXCHANGE
    // ============================================================

    async _newTokenRequest(paramList) {
        let bodyList = []
        for (let i = 0; i < paramList.length; i++) {
            bodyList.push(paramList[i][0] + '=' + encodeURIComponent(paramList[i][1]))
        }
        let body = bodyList.join('&')

        let headers = this.getSignHeaders()
        headers['Content-Type'] = 'application/x-www-form-urlencoded'
        headers['Host'] = 'oauth.secure.pixiv.net'

        Network.deleteCookies('https://oauth.secure.pixiv.net')

        console.log('[Pixiv] _requestToken POST to ' + Pixiv.AUTH_URL)
        let res = await Network.post(Pixiv.AUTH_URL, headers, body)
        console.log('[Pixiv] _requestToken response status=' + res.status)
        if (res.status !== 200) {
            console.log('[Pixiv] _requestToken FAILED, body (first 300): ' + res.body.substring(0, 300))
            return null
        }

        let json = JSON.parse(res.body)
        let resp = json.response
        if (!resp || !resp.access_token) {
            console.log('[Pixiv] _requestToken: no access_token in response')
            return null
        }

        console.log('[Pixiv] _requestToken SUCCESS, got access_token')
        this._saveTokenResponse(resp)
        return resp.access_token
    }

    async _exchangeAuthCode() {
        let code = this.loadData('_pkce_code')
        let verifier = Pixiv._pkceVerifier
        if (!code || !verifier) return false

        this.deleteData('_pkce_code')

        let result = await this._newTokenRequest([
            ['client_id',       Pixiv.CLIENT_ID],
            ['client_secret',   Pixiv.CLIENT_SECRET],
            ['grant_type',      'authorization_code'],
            ['code',            code],
            ['code_verifier',   verifier],
            ['redirect_uri',    Pixiv.REDIRECT_URI],
            ['include_policy',  'true']
        ])
        return !!result
    }

    async _exchangeWebviewToken() {
        let token = this.loadData('pending_refresh_token')
        if (!token) return false
        this.deleteData('pending_refresh_token')
        this.saveData('refresh_token', token)

        let result = await this._newTokenRequest([
            ['client_id',       Pixiv.CLIENT_ID],
            ['client_secret',   Pixiv.CLIENT_SECRET],
            ['grant_type',      'refresh_token'],
            ['refresh_token',   token],
            ['include_policy',  'true']
        ])
        return !!result
    }

    async refreshToken() {
        let refreshToken = this.loadData('refresh_token')
        if (!refreshToken) throw 'No refresh token'

        let result = await this._newTokenRequest([
            ['client_id',       Pixiv.CLIENT_ID],
            ['client_secret',   Pixiv.CLIENT_SECRET],
            ['grant_type',      'refresh_token'],
            ['refresh_token',   refreshToken],
            ['include_policy',  'true']
        ])
        if (!result) throw 'Token refresh failed'
        return result
    }

    _saveTokenResponse(resp) {
        this.saveData('access_token', resp.access_token)
        this.saveData('refresh_token', resp.refresh_token)
        if (resp.user) {
            this.saveData('user_id', resp.user.id.toString())
            this.saveData('user_name', resp.user.name)
            this.saveData('user_account', resp.user.account)
        }
    }

    // ============================================================
    //  OAUTH ERROR DETECTION
    // ============================================================

    _isOAuthError(res) {
        if (!res) return false
        if (res.status === 400 || res.status === 401) {
            try {
                let json = JSON.parse(res.body)
                let msg = json?.error?.message || json?.errors?.system?.message || ''
                if (msg.indexOf('OAuth') !== -1) return true
            } catch (e) {}
            if (res.status === 401) return true
        }
        return false
    }

    // ============================================================
    //  HTTP HELPERS
    // ============================================================

    async _ensureToken() {
        if (this.loadData('pending_refresh_token')) {
            console.log('[Pixiv] _ensureToken: found pending_refresh_token, exchanging...')
            try { await this._exchangeWebviewToken() } catch (e) {
                console.log('[Pixiv] _ensureToken: _exchangeWebviewToken error: ' + e)
            }
        }
        if (this.loadData('_pkce_code')) {
            console.log('[Pixiv] _ensureToken: found _pkce_code, exchanging...')
            try { await this._exchangeAuthCode() } catch (e) {
                console.log('[Pixiv] _ensureToken: _exchangeAuthCode error: ' + e)
            }
        }
        let hasAccessToken = !!this.loadData('access_token')
        console.log('[Pixiv] _ensureToken done, has access_token=' + hasAccessToken)
    }

    async apiGet(url) {
        console.log('[Pixiv] apiGet: ' + url.substring(0, 80))
        await this._ensureToken()
        let headers = this.getApiHeaders()
        if (!headers) {
            console.log('[Pixiv] apiGet: FAILED - getApiHeaders returned null')
            throw 'Login expired'
        }

        let res = await Network.get(url, headers)
        console.log('[Pixiv] apiGet response status=' + res.status)
        if (this._isOAuthError(res)) {
            await this.refreshToken()
            headers = this.getApiHeaders()
            res = await Network.get(url, headers)
        }
        if (res.status !== 200) throw 'HTTP ' + res.status + ': ' + url
        return JSON.parse(res.body)
    }

    async apiPost(url, body) {
        await this._ensureToken()
        let headers = this.getPostHeaders()
        if (!headers) throw 'Login expired'

        let res = await Network.post(url, headers, body)
        if (this._isOAuthError(res)) {
            await this.refreshToken()
            headers = this.getPostHeaders()
            res = await Network.post(url, headers, body)
        }
        if (res.status !== 200) throw 'HTTP ' + res.status + ': ' + url
        return JSON.parse(res.body)
    }

    // ============================================================
    //  UTILITY
    // ============================================================

    parseIllust(illust) {
        let cover = illust.image_urls.medium
        if (illust.page_count > 1 && illust.meta_pages && illust.meta_pages.length > 0) {
            cover = illust.meta_pages[0].image_urls.medium
        }
        let tags = (illust.tags || []).map(function(t) { return t.translated_name || t.name })
        tags.push(illust.user.name)
        return new Comic({
            id: illust.id.toString(),
            title: illust.title,
            subTitle: illust.user.name,
            cover: cover,
            tags: tags,
            description: (illust.caption || '').replace(/<[^>]*>/g, ''),
            maxPage: illust.page_count || 1
        })
    }

    parseUserPreview(userPreview) {
        let user = userPreview.user
        let illusts = userPreview.illusts || []
        let cover = user.profile_image_urls.medium
        let tags = []
        let pages = 1
        if (illusts.length > 0) {
            cover = illusts[0].image_urls.medium
            tags = (illusts[0].tags || []).map(function(t) { return t.translated_name || t.name })
            pages = illusts.length
        }
        return new Comic({
            id: 'user_' + user.id.toString(),
            title: user.name,
            subTitle: user.account,
            cover: cover,
            tags: tags,
            description: '',
            maxPage: pages
        })
    }

    // ============================================================
    //  EXPLORE
    // ============================================================

    explore = [
        {
            title: "Following",
            type: "multiPageComicList",

            loadNext: async (next) => {
                let url = next
                    ? (next.startsWith('http') ? next : this.apiBase + next)
                    : this.apiBase + '/v2/illust/follow?restrict=all'

                let json = await this.apiGet(url)
                let comics = (json.illusts || []).map((function(e) { return this.parseIllust(e) }).bind(this))

                return { comics: comics, next: json.next_url || null }
            },
        }
    ]

    // ============================================================
    //  CATEGORY — trending tags as dynamic discovery (ref: PixEz)
    // ============================================================

    category = {
        title: "Pixiv",
        parts: [
            {
                name: "Trending",
                type: "dynamic",
                loader: async () => {
                    try {
                        let json = await this.apiGet(
                            this.apiBase + '/v1/trending-tags/illust?filter=for_android')
                        let tags = json.trend_tags || []
                        return tags.map(function(t) {
                            return {
                                label: t.translated_name || t.tag,
                                target: {
                                    page: 'category',
                                    attributes: {
                                        category: 'tag_search',
                                        param: t.tag
                                    }
                                }
                            }
                        })
                    } catch (e) {
                        console.log('[Pixiv] Trending tags load failed: ' + e)
                        return []
                    }
                },
            }
        ],
        enableRankingPage: false,
    }

    categoryComics = {
        load: async (category, param, options, page) => {
            // tag_search: trending/via-tag results
            if (category === 'tag_search') {
                let url
                if (page > 1) {
                    let cursor = this.loadData('_tag_cursor')
                    if (!cursor) return { comics: [], maxPage: page - 1 }
                    url = this.apiBase + cursor
                } else {
                    this.deleteData('_tag_cursor')
                    url = this.apiBase + '/v1/search/illust' +
                        '?word=' + encodeURIComponent(param) +
                        '&search_target=exact_match_for_tags' +
                        '&sort=popular_desc' +
                        '&filter=for_android' +
                        '&merge_plain_keyword_results=true'
                }
                let json = await this.apiGet(url)
                let illusts = json.illusts || []
                let comics = illusts.map((function(e) { return this.parseIllust(e) }).bind(this))
                if (json.next_url) {
                    this.saveData('_tag_cursor', json.next_url)
                } else {
                    this.deleteData('_tag_cursor')
                }
                return { comics: comics, maxPage: json.next_url ? page + 1 : page }
            }
            // user_illusts: artist works (offset-based pagination)
            if (category === 'user_illusts') {
                let offset = (page - 1) * 30
                let json = await this.apiGet(
                    this.apiBase + '/v1/user/illusts?filter=for_android&user_id=' + param + '&offset=' + offset)
                let illusts = json.illusts || []
                let comics = illusts.map((function(e) { return this.parseIllust(e) }).bind(this))
                let maxPage = illusts.length < 30 ? page : page + 1
                return { comics: comics, maxPage: maxPage }
            }
            return { comics: [], maxPage: 1 }
        },
    }

    // ============================================================
    //  SEARCH — cursor-based via loadNext
    //
    //  Architecture (matches PixEz):
    //   Tag clicks  → isTagClick → search/illust
    //                 (exact_match_for_tags, popular_desc)
    //   Search bar  → !isTagClick → search/illust
    //                 (user-chosen sort/search_target/ai filters)
    //   User search → searchTarget='users' → search/user
    // ============================================================

    search = {

        loadNext: async (keyword, options, next) => {
            let sort = ((options && options[0]) || 'date_desc').replace(/^"|"$/g, '')
            let searchTarget = ((options && options[1]) || 'partial_match_for_tags').replace(/^"|"$/g, '')
            let aiFilter = ((options && options[2]) || 'all').replace(/^"|"$/g, '')

            let isTagClick = this._pendingTagSearch
            this._pendingTagSearch = false

            let url

            if (next) {
                url = next.startsWith('http') ? next : this.apiBase + next
            } else {
                if (searchTarget === 'users') {
                    url = this.apiBase + '/v1/search/user' +
                        '?word=' + encodeURIComponent(keyword) +
                        '&filter=for_android'
                } else if (isTagClick) {
                    url = this.apiBase + '/v1/search/illust' +
                        '?word=' + encodeURIComponent(keyword) +
                        '&search_target=exact_match_for_tags' +
                        '&sort=popular_desc' +
                        '&filter=for_android' +
                        '&merge_plain_keyword_results=true'
                } else {
                    url = this.apiBase + '/v1/search/illust' +
                        '?word=' + encodeURIComponent(keyword) +
                        '&sort=' + sort +
                        '&search_target=' + searchTarget +
                        '&filter=for_android' +
                        '&merge_plain_keyword_results=true' +
                        (aiFilter === 'exclude_ai' ? '&search_ai_type=1' : '') +
                        (aiFilter === 'only_ai' ? '&search_ai_type=2' : '')
                }
            }

            let json = await this.apiGet(url)
            let comics

            if (searchTarget === 'users') {
                let userPreviews = json.user_previews || []
                comics = userPreviews.map((function(e) { return this.parseUserPreview(e) }).bind(this))
            } else {
                comics = (json.illusts || []).map((function(e) { return this.parseIllust(e) }).bind(this))
            }

            return { comics: comics, next: json.next_url || null }
        },

        optionList: [
            {
                type: "select",
                options: [
                    "date_desc-Newest",
                    "date_asc-Oldest",
                    "popular_desc-Popular"
                ],
                label: "sort",
                default: "date_desc",
            },
            {
                type: "select",
                options: [
                    "partial_match_for_tags-Tag Match",
                    "exact_match_for_tags-Exact Tag",
                    "title_and_caption-Title & Caption",
                    "users-Users"
                ],
                label: "target",
                default: "partial_match_for_tags",
            },
            {
                type: "select",
                options: [
                    "all-All",
                    "exclude_ai-No AI",
                    "only_ai-AI Only"
                ],
                label: "ai",
                default: "all",
            }
        ],

        enableTagsSuggestions: false,
    }

    // ============================================================
    //  FAVORITES — bookmark system using Pixiv bookmark tags as folders
    // ============================================================

    favorites = {
        multiFolder: true,

        addOrDelFavorite: async (comicId, folderId, isAdding, favoriteId) => {
            if (isAdding) {
                let body = 'illust_id=' + comicId + '&restrict=public'
                if (folderId) {
                    body += '&tags%5B%5D=' + encodeURIComponent(folderId)
                }
                await this.apiPost(this.apiBase + '/v2/illust/bookmark/add', body)
            } else {
                let body = 'illust_id=' + comicId
                await this.apiPost(this.apiBase + '/v1/illust/bookmark/delete', body)
            }
            return 'ok'
        },

        loadFolders: async (comicId) => {
            let userId = this.loadData('user_id')
            if (!userId) throw 'Login expired'

            let json = await this.apiGet(
                this.apiBase + '/v1/user/bookmark-tags/illust?user_id=' + userId + '&restrict=public')
            let tags = json.bookmark_tags || []

            let folders = { '': 'Default' }
            tags.forEach(function(t) {
                folders[t.name] = t.name + ' (' + t.count + ')'
            })

            let favorited = []
            if (comicId) {
                try {
                    let detail = await this.apiGet(
                        this.apiBase + '/v2/illust/bookmark/detail?illust_id=' + comicId)
                    let bd = detail.bookmark_detail
                    if (bd && bd.is_bookmarked) {
                        (bd.tags || []).forEach(function(t) { favorited.push(t.name) })
                    }
                } catch (e) {}
            }

            return { folders: folders, favorited: favorited }
        },

        loadComics: async (page, folder) => {
            let userId = this.loadData('user_id')
            if (!userId) throw 'Login expired'

            let offset = (page - 1) * 30
            let url = this.apiBase + '/v1/user/bookmarks/illust' +
                '?user_id=' + userId + '&restrict=public&offset=' + offset
            if (folder) url += '&tag=' + encodeURIComponent(folder)

            let json = await this.apiGet(url)
            let illusts = json.illusts || []
            let comics = illusts.map((function(e) { return this.parseIllust(e) }).bind(this))
            let maxPage = illusts.length < 30 ? page : page + 1
            return { comics: comics, maxPage: maxPage }
        },
    }

    // ============================================================
    //  COMIC
    // ============================================================

    comic = {

        loadInfo: async (id) => {
            if (id.startsWith('user_')) {
                let userId = id.substring(5)
                let json = await this.apiGet(
                    this.apiBase + '/v1/user/illusts?filter=for_android&user_id=' + userId + '&offset=0')
                let illusts = json.illusts || []
                if (illusts.length === 0) {
                    let userJson = await this.apiGet(
                        this.apiBase + '/v1/user/detail?filter=for_android&user_id=' + userId)
                    let user = userJson.user
                    if (!user) throw 'User not found'
                    let tagsObj = {}
                    tagsObj['Artist'] = [user.name + ' |' + user.id]

                    let isFollowed = false
                    if (this.loadData('user_id')) {
                        try {
                            let followJson = await this.apiGet(
                                this.apiBase + '/v1/user/follow/detail?user_id=' + userId)
                            let fd = followJson.follow_detail
                            if (fd) isFollowed = !!fd.is_followed
                        } catch (e) {}
                    }
                    this.saveData('_artist_of_' + userId, userId)

                    return new ComicDetails({
                        title: user.name,
                        subtitle: user.account,
                        cover: user.profile_image_urls.medium,
                        description: user.comment || '',
                        tags: tagsObj,
                        chapters: { '0': user.name },
                        isLiked: isFollowed,
                        url: 'https://www.pixiv.net/users/' + user.id
                    })
                }
                let illust = illusts[0]
                // Reuse existing illust detail loading
                return await this.comic.loadInfo(illust.id.toString())
            }

            let json = await this.apiGet(
                this.apiBase + '/v1/illust/detail?illust_id=' + id)
            let illust = json.illust
            if (!illust) throw 'Illust not found'

            let chapters = {}
            chapters['0'] = illust.title

            let tagsObj = {}
            let contentTags = (illust.tags || []).map(function(t) {
                if (t.translated_name && t.translated_name !== t.name) {
                    return t.name + ' [' + t.translated_name + ']'
                }
                return t.name
            })
            if (contentTags.length > 0) tagsObj['Tags'] = contentTags
            tagsObj['Artist'] = [illust.user.name + ' |' + illust.user.id]

            this.saveData('_artist_of_' + illust.id, illust.user.id)

            let isFollowed = false
            if (this.loadData('user_id')) {
                try {
                    let followJson = await this.apiGet(
                        this.apiBase + '/v1/user/follow/detail?user_id=' + illust.user.id)
                    let fd = followJson.follow_detail
                    if (fd) isFollowed = !!fd.is_followed
                } catch (e) {}
            }

            return new ComicDetails({
                title: illust.title,
                subtitle: illust.user.name,
                cover: illust.image_urls.medium,
                description: illust.caption || '',
                tags: tagsObj,
                chapters: chapters,
                isFavorite: illust.is_bookmarked || false,
                url: 'https://www.pixiv.net/artworks/' + illust.id,
                commentCount: illust.total_comments || 0,
                likesCount: illust.total_bookmarks || 0,
                isLiked: isFollowed,
                uploadTime: illust.create_date,
                maxPage: illust.page_count || 1
            })
        },

        loadEp: async (comicId, epId) => {
            let json = await this.apiGet(
                this.apiBase + '/v1/illust/detail?illust_id=' + comicId)
            let illust = json.illust
            if (!illust) throw 'Illust not found'

            let images = []
            if (illust.page_count <= 1 || !illust.meta_pages || illust.meta_pages.length === 0) {
                let url = illust.meta_single_page?.original_image_url
                    || illust.image_urls.large
                images.push(url)
            } else {
                for (let i = 0; i < illust.meta_pages.length; i++) {
                    let page = illust.meta_pages[i]
                    images.push(page.image_urls.original || page.image_urls.large)
                }
            }
            return { images: images }
        },

        onImageLoad: (url, comicId, epId) => {
            return {
                headers: {
                    'Referer': 'https://app-api.pixiv.net/',
                    'User-Agent': Pixiv.USER_AGENT
                }
            }
        },

        onThumbnailLoad: (url) => {
            return {
                headers: {
                    'Referer': 'https://app-api.pixiv.net/',
                    'User-Agent': Pixiv.USER_AGENT
                }
            }
        },

        // Artist follow/unfollow via like button.
        // Ignores Venera's isLike param — toggles based on actual server state.
        likeComic: async (id, isLike) => {
            let artistId = this.loadData('_artist_of_' + id)
            if (!artistId && id.startsWith('user_')) {
                artistId = id.substring(5)
            }
            if (!artistId) return

            let isFollowed = false
            try {
                let followJson = await this.apiGet(
                    this.apiBase + '/v1/user/follow/detail?user_id=' + artistId)
                let fd = followJson.follow_detail
                if (fd) isFollowed = !!fd.is_followed
            } catch (e) {}

            if (isFollowed) {
                let body = 'user_id=' + artistId
                await this.apiPost(this.apiBase + '/v1/user/follow/delete', body)
            } else {
                let body = 'user_id=' + artistId + '&restrict=private'
                await this.apiPost(this.apiBase + '/v1/user/follow/add', body)
            }
        },

        // ============================================================
        //  COMMENTS
        // ============================================================

        loadComments: async (comicId, subId, page, replyTo) => {
            let cursorKey = '_comment_cursor_' + comicId + (replyTo ? '_' + replyTo : '_root')
            let url

            if (page > 1) {
                let cursor = this.loadData(cursorKey)
                if (!cursor) return { comments: [], maxPage: page - 1 }
                url = this.apiBase + cursor
            } else {
                this.deleteData(cursorKey)
                if (replyTo) {
                    url = this.apiBase + '/v2/illust/comment/replies?comment_id=' + replyTo
                } else {
                    url = this.apiBase + '/v3/illust/comments?illust_id=' + comicId
                }
            }

            let json = await this.apiGet(url)
            let comments = (json.comments || []).map(function(c) {
                return new Comment({
                    userName: c.user.name,
                    avatar: c.user.profile_image_urls.medium,
                    content: c.comment,
                    time: c.date,
                    replyCount: c.has_replies ? 1 : null,
                    id: c.id.toString(),
                })
            })

            if (json.next_url) {
                this.saveData(cursorKey, json.next_url)
            } else {
                this.deleteData(cursorKey)
            }

            return { comments: comments, maxPage: json.next_url ? page + 1 : page }
        },

        sendComment: async (comicId, subId, content, replyTo) => {
            let body = 'illust_id=' + encodeURIComponent(comicId) +
                '&comment=' + encodeURIComponent(content)
            if (replyTo) {
                body += '&parent_comment_id=' + encodeURIComponent(replyTo)
            }
            await this.apiPost(this.apiBase + '/v1/illust/comment/add', body)
            return 'ok'
        },

        // Pixiv does not support comment likes/votes — stubs for Venera framework
        likeComment: async (comicId, subId, commentId, isLike) => { },

        voteComment: async (id, subId, commentId, isUp, isCancel) => { },

        onClickTag: (namespace, tag) => {
            if (namespace === 'Artist') {
                let idx = tag.lastIndexOf('|')
                if (idx !== -1) {
                    return {
                        page: 'category',
                        attributes: {
                            category: 'user_illusts',
                            param: tag.substring(idx + 1).trim()
                        }
                    }
                }
            }
            if (tag && tag.startsWith('artist:')) {
                return {
                    page: 'category',
                    attributes: {
                        category: 'user_illusts',
                        param: tag.substring(7)
                    }
                }
            }
            // Extract original name from "original [translated]" format
            let searchTag = tag
            let bracketIdx = tag.lastIndexOf(' [')
            if (bracketIdx !== -1 && tag.endsWith(']')) {
                searchTag = tag.substring(0, bracketIdx)
            }
            this._pendingTagSearch = true
            return {
                page: 'search',
                attributes: {
                    keyword: searchTag,
                },
            }
        },

        idMatch: "^\\d+$",
    }

    // ============================================================
    //  ACCOUNT
    //
    //  PKCE flow (Pixiv official App login):
    //    WebView opens app-api.pixiv.net/web/v1/login?code_challenge=...
    //    → server creates PKCE session → redirects to accounts.pixiv.net/login
    //    → user logs in → Pixiv redirects through PKCE start → callback?code=...
    //    → checkStatus captures code → onLoginSuccess exchanges for token
    //
    //  Fallback: localStorage extraction + manual refresh_token
    // ============================================================

    account = {

        loginWithWebview: {
            url: (function() {
                let chars = Pixiv.PKCE_CHARS
                let verifier = ''
                for (let i = 0; i < 128; i++) verifier += chars[randomInt(0, chars.length - 1)]
                Pixiv._pkceVerifier = verifier
                let hash = Convert.sha256(Convert.encodeUtf8(verifier))
                let b64 = Convert.encodeBase64(hash)
                let challenge = ''
                for (let i = 0; i < b64.length; i++) {
                    let c = b64[i]
                    if (c === '+') challenge += '-'
                    else if (c === '/') challenge += '_'
                    else if (c === '=') break
                    else challenge += c
                }
                return 'https://app-api.pixiv.net/web/v1/login' +
                    '?code_challenge=' + challenge +
                    '&code_challenge_method=S256' +
                    '&client=pixiv-android'
            })(),

            checkStatus: (url, title) => {
                console.log('[Pixiv] checkStatus url=' + url)

                // PKCE callback: Pixiv redirects here with auth code after login
                let codeIdx = url.indexOf('code=')
                if (url.indexOf('/auth/pixiv/callback') !== -1 && codeIdx !== -1) {
                    console.log('[Pixiv] checkStatus → PKCE callback, capturing code')
                    let start = codeIdx + 5
                    let end = url.indexOf('&', start)
                    if (end === -1) end = url.length
                    let code = url.substring(start, end)
                    if (code) {
                        this.saveData('_pkce_code', decodeURIComponent(code))
                        console.log('[Pixiv] PKCE code saved')
                        return true
                    }
                }

                return false
            },

            onLoginSuccess: () => {
                console.log('[Pixiv] onLoginSuccess triggered')
                let code = this.loadData('_pkce_code')
                if (!code) {
                    console.log('[Pixiv] WARN: no PKCE code in onLoginSuccess')
                    return
                }
                console.log('[Pixiv] Exchanging PKCE code...')
                this._exchangeAuthCode().then(function(ok) {
                    console.log('[Pixiv] _exchangeAuthCode result=' + ok)
                    if (ok) this._regeneratePkce()
                }.bind(this)).catch(function(e) {
                    console.log('[Pixiv] _exchangeAuthCode error=' + e)
                })
            },
        },

        login: async (account, pwd) => {
            console.log('[Pixiv] login() called, account=' + !!account)

            // 1) Exchange pending PKCE auth code
            let code = this.loadData('_pkce_code')
            if (code) {
                console.log('[Pixiv] login: path 1 - PKCE code exchange')
                let ok = await this._exchangeAuthCode()
                if (ok) return 'ok'
                throw 'Login failed: unable to exchange authorization code'
            }

            // 2) Exchange pending webview token
            let pending = this.loadData('pending_refresh_token')
            if (pending) {
                console.log('[Pixiv] login: path 2 - pending refresh_token exchange')
                let ok = await this._exchangeWebviewToken()
                if (ok) return 'ok'
                throw 'Login failed: unable to exchange webview token'
            }

            // 3) Refresh existing stored token
            if (this.loadData('refresh_token')) {
                console.log('[Pixiv] login: path 3 - refresh existing token')
                try {
                    await this.refreshToken()
                    return 'ok'
                } catch (e) {
                    throw 'Login failed: unable to refresh token'
                }
            }

            // 4) Manual refresh_token via account parameter
            let manual = (account || '').trim()
            if (manual) {
                console.log('[Pixiv] login: path 4 - manual refresh_token')
                this.saveData('refresh_token', manual)
                try {
                    await this.refreshToken()
                    return 'ok'
                } catch (e) {
                    this.deleteData('refresh_token')
                    throw 'Login failed: invalid refresh token'
                }
            }

            console.log('[Pixiv] login: FAILED - no token available')
            throw 'Please login via WebView first, or provide a valid refresh_token'
        },

        logout: () => {
            this.deleteData('access_token')
            this.deleteData('refresh_token')
            this.deleteData('pending_refresh_token')
            this.deleteData('_pkce_code')
            this.deleteData('user_id')
            this.deleteData('user_name')
            this.deleteData('user_account')
            Network.deleteCookies('https://www.pixiv.net')
            Network.deleteCookies('https://accounts.pixiv.net')
        },

        registerWebsite: 'https://www.pixiv.net/signup/'
    }

    // ============================================================
    //  SETTINGS
    // ============================================================

    settings = {
        apiHost: {
            title: "API Host",
            type: "input",
            default: "https://app-api.pixiv.net",
            validator: "^https?://.+"
        }
    }

    // ============================================================
    //  TRANSLATION
    // ============================================================

    translation = {
        'zh_CN': {
            'API Host': 'API 地址',
            'Following': '关注',
            'sort': '排序',
            'target': '搜索目标',
            'ai': 'AI',
            'Newest': '最新',
            'Oldest': '最旧',
            'Popular': '最热',
            'Tag Match': '标签匹配',
            'Exact Tag': '精确标签',
            'Title & Caption': '标题和简介',
            'All': '全部',
            'No AI': '不含AI',
            'AI Only': '仅AI',
            'Users': '用户',
            'Trending': '热门标签',
        },
        'zh_TW': {},
        'en': {}
    }
}
