/** @type {import('./_venera_.js')} */

class Pixiv extends ComicSource {

    // ============================================================
    //  BASIC INFO
    // ============================================================
    name = "Pixiv"
    key = "pixiv"
    version = "0.2.2"
    minAppVersion = "1.6.0"
    url = "https://cdn.jsdelivr.net/gh/theoldman-lab/venera-configs@main/pixiv.js"

    // ============================================================
    //  CONSTANTS
    // ============================================================
    static AUTH_URL      = "https://oauth.secure.pixiv.net/auth/token"
    static CLIENT_ID     = "MOBrBDS8blbauoSck0ZfDbtuzpyT"
    static CLIENT_SECRET = "lsACyCD94FhDUtGTXi3QzcFE2uU1hqtDaKeqrdwj"
    static HASH_SECRET   = "28c1fdd170a5204386cb1313c7077b34f83e4aaf4aa829ce78c231e05b0bae2c"
    static USER_AGENT    = "PixivAndroidApp/5.0.166 (Android 10.0; Pixel C)"
    static REDIRECT_URI  = "https://app-api.pixiv.net/web/v1/users/auth/pixiv/callback"
    static PKCE_CHARS    = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"

    static _pkceVerifier = ""
    static LOGIN_URL     = "https://accounts.pixiv.net/login?lang=en"

    get apiBase() {
        return this.loadSetting('apiHost') || 'https://app-api.pixiv.net'
    }

    // ============================================================
    //  INIT — regenerate PKCE challenge for fresh sessions
    // ============================================================

    init() {
        // PKCE already generated by IIFE in loginWithWebview.url
    }

    _regeneratePkce() {
        let chars = Pixiv.PKCE_CHARS
        let verifier = ''
        for (let i = 0; i < 128; i++) {
            verifier += chars[randomInt(0, chars.length - 1)]
        }
        Pixiv._pkceVerifier = verifier

        let hash = Convert.sha256(Convert.encodeUtf8(verifier))
        let b64 = Convert.encodeBase64(hash)
        let challenge = ''
        for (let i = 0; i < b64.length; i++) {
            let c = b64[i]
            if (c === '+') challenge += '-'
            else if (c === '/') challenge += '_'
            else if (c === '=') break
            else challenge += c
        }

        this.account.loginWithWebview.url =
            'https://app-api.pixiv.net/web/v1/login' +
            '?code_challenge=' + challenge +
            '&code_challenge_method=S256' +
            '&client=pixiv-android'
    }

    // ============================================================
    //  SIGN HEADERS
    // ============================================================

    getSignHeaders() {
        let d = new Date()
        let time = d.toISOString().replace(/\.\d+Z$/, '+00:00')
        let hash = Convert.hexEncode(
            Convert.md5(Convert.encodeUtf8(time + Pixiv.HASH_SECRET))
        )
        return {
            'X-Client-Time':    time,
            'X-Client-Hash':    hash,
            'User-Agent':       Pixiv.USER_AGENT,
            'App-OS':           'Android',
            'App-OS-Version':   'Android 10.0',
            'App-Version':      '5.0.166',
            'Accept-Language':  'zh-cn'
        }
    }

    getApiHeaders() {
        let token = this.loadData('access_token')
        if (!token) return null
        let h = this.getSignHeaders()
        h['Authorization'] = 'Bearer ' + token
        h['Host'] = 'app-api.pixiv.net'
        return h
    }

    getPostHeaders() {
        let h = this.getApiHeaders()
        if (!h) return null
        h['Content-Type'] = 'application/x-www-form-urlencoded'
        return h
    }

    // ============================================================
    //  LOCAL STORAGE TOKEN EXTRACTION (fallback)
    // ============================================================

    _tryLocalStorageToken() {
        let storage = this.loadData('_localStorage')
        console.log('[Pixiv] _tryLocalStorageToken: exists=' + !!storage)
        if (!storage) return false

        if (typeof storage === 'string') {
            try { storage = JSON.parse(storage) } catch(e) { return false }
        }
        if (!storage || typeof storage !== 'object') return false

        let keys = Object.keys(storage)
        console.log('[Pixiv] localStorage keys (' + keys.length + '): ' + keys.join(', '))

        let refreshToken = null
        if (storage.refresh_token) refreshToken = storage.refresh_token
        if (!refreshToken && storage.token) {
            let t = typeof storage.token === 'string' ? JSON.parse(storage.token) : storage.token
            if (t && t.refresh_token) refreshToken = t.refresh_token
        }
        if (!refreshToken) {
            for (let key in storage) {
                try {
                    let v = typeof storage[key] === 'string' ? JSON.parse(storage[key]) : storage[key]
                    if (v && v.refresh_token) { refreshToken = v.refresh_token; break }
                } catch (e) {}
            }
        }

        if (refreshToken) {
            console.log('[Pixiv] localStorage: refresh_token found')
            this.saveData('pending_refresh_token', refreshToken)
            return true
        }
        console.log('[Pixiv] localStorage: no refresh_token')
        return false
    }

    // ============================================================
    //  TOKEN EXCHANGE
    // ============================================================

    async _newTokenRequest(paramList) {
        let bodyList = []
        for (let i = 0; i < paramList.length; i++) {
            bodyList.push(paramList[i][0] + '=' + encodeURIComponent(paramList[i][1]))
        }
        let body = bodyList.join('&')

        let headers = this.getSignHeaders()
        headers['Content-Type'] = 'application/x-www-form-urlencoded'
        headers['Host'] = 'oauth.secure.pixiv.net'

        Network.deleteCookies('https://oauth.secure.pixiv.net')

        console.log('[Pixiv] _requestToken POST to ' + Pixiv.AUTH_URL)
        let res = await Network.post(Pixiv.AUTH_URL, headers, body)
        console.log('[Pixiv] _requestToken response status=' + res.status)
        if (res.status !== 200) {
            console.log('[Pixiv] _requestToken FAILED, body (first 300): ' + res.body.substring(0, 300))
            return null
        }

        let json = JSON.parse(res.body)
        let resp = json.response
        if (!resp || !resp.access_token) {
            console.log('[Pixiv] _requestToken: no access_token in response')
            return null
        }

        console.log('[Pixiv] _requestToken SUCCESS, got access_token')
        this._saveTokenResponse(resp)
        return resp.access_token
    }

    async _exchangeAuthCode() {
        let code = this.loadData('_pkce_code')
        let verifier = Pixiv._pkceVerifier
        if (!code || !verifier) return false

        this.deleteData('_pkce_code')

        let result = await this._newTokenRequest([
            ['client_id',       Pixiv.CLIENT_ID],
            ['client_secret',   Pixiv.CLIENT_SECRET],
            ['grant_type',      'authorization_code'],
            ['code',            code],
            ['code_verifier',   verifier],
            ['redirect_uri',    Pixiv.REDIRECT_URI],
            ['include_policy',  'true']
        ])
        return !!result
    }

    async _exchangeWebviewToken() {
        let token = this.loadData('pending_refresh_token')
        if (!token) return false
        this.deleteData('pending_refresh_token')
        this.saveData('refresh_token', token)

        let result = await this._newTokenRequest([
            ['client_id',       Pixiv.CLIENT_ID],
            ['client_secret',   Pixiv.CLIENT_SECRET],
            ['grant_type',      'refresh_token'],
            ['refresh_token',   token],
            ['include_policy',  'true']
        ])
        return !!result
    }

    async refreshToken() {
        let refreshToken = this.loadData('refresh_token')
        if (!refreshToken) throw 'No refresh token'

        let result = await this._newTokenRequest([
            ['client_id',       Pixiv.CLIENT_ID],
            ['client_secret',   Pixiv.CLIENT_SECRET],
            ['grant_type',      'refresh_token'],
            ['refresh_token',   refreshToken],
            ['include_policy',  'true']
        ])
        if (!result) throw 'Token refresh failed'
        return result
    }

    _saveTokenResponse(resp) {
        this.saveData('access_token', resp.access_token)
        this.saveData('refresh_token', resp.refresh_token)
        if (resp.user) {
            this.saveData('user_id', resp.user.id.toString())
            this.saveData('user_name', resp.user.name)
            this.saveData('user_account', resp.user.account)
        }
    }

    // ============================================================
    //  OAUTH ERROR DETECTION
    // ============================================================

    _isOAuthError(res) {
        if (!res) return false
        if (res.status === 400 || res.status === 401) {
            try {
                let json = JSON.parse(res.body)
                let msg = json?.error?.message || json?.errors?.system?.message || ''
                if (msg.indexOf('OAuth') !== -1) return true
            } catch (e) {}
            if (res.status === 401) return true
        }
        return false
    }

    // ============================================================
    //  HTTP HELPERS
    // ============================================================

    async _ensureToken() {
        if (this.loadData('pending_refresh_token')) {
            console.log('[Pixiv] _ensureToken: found pending_refresh_token, exchanging...')
            try { await this._exchangeWebviewToken() } catch (e) {
                console.log('[Pixiv] _ensureToken: _exchangeWebviewToken error: ' + e)
            }
        }
        if (this.loadData('_pkce_code')) {
            console.log('[Pixiv] _ensureToken: found _pkce_code, exchanging...')
            try { await this._exchangeAuthCode() } catch (e) {
                console.log('[Pixiv] _ensureToken: _exchangeAuthCode error: ' + e)
            }
        }
        let hasAccessToken = !!this.loadData('access_token')
        console.log('[Pixiv] _ensureToken done, has access_token=' + hasAccessToken)
    }

    async apiGet(url) {
        console.log('[Pixiv] apiGet: ' + url.substring(0, 80))
        await this._ensureToken()
        let headers = this.getApiHeaders()
        if (!headers) {
            console.log('[Pixiv] apiGet: FAILED - getApiHeaders returned null')
            throw 'Login expired'
        }

        let res = await Network.get(url, headers)
        console.log('[Pixiv] apiGet response status=' + res.status)
        if (this._isOAuthError(res)) {
            await this.refreshToken()
            headers = this.getApiHeaders()
            res = await Network.get(url, headers)
        }
        if (res.status !== 200) throw 'HTTP ' + res.status + ': ' + url
        return JSON.parse(res.body)
    }

    async apiPost(url, body) {
        await this._ensureToken()
        let headers = this.getPostHeaders()
        if (!headers) throw 'Login expired'

        let res = await Network.post(url, headers, body)
        if (this._isOAuthError(res)) {
            await this.refreshToken()
            headers = this.getPostHeaders()
            res = await Network.post(url, headers, body)
        }
        if (res.status !== 200) throw 'HTTP ' + res.status + ': ' + url
        return JSON.parse(res.body)
    }

    // ============================================================
    //  UTILITY
    // ============================================================

    parseIllust(illust) {
        let cover = illust.image_urls.medium
        if (illust.page_count > 1 && illust.meta_pages && illust.meta_pages.length > 0) {
            cover = illust.meta_pages[0].image_urls.medium
        }
        let tags = (illust.tags || []).map(function(t) { return t.translated_name || t.name })
        tags.push(illust.user.name)
        return new Comic({
            id: illust.id.toString(),
            title: illust.title,
            subTitle: illust.user.name,
            cover: cover,
            tags: tags,
            description: (illust.caption || '').replace(/<[^>]*>/g, ''),
            maxPage: illust.page_count || 1
        })
    }

    // ============================================================
    //  EXPLORE
    // ============================================================

    explore = [
        {
            title: "Following",
            type: "multiPageComicList",

            loadNext: async (next) => {
                let url = next
                    ? (next.startsWith('http') ? next : this.apiBase + next)
                    : this.apiBase + '/v2/illust/follow?restrict=all'

                let json = await this.apiGet(url)
                let comics = (json.illusts || []).map((function(e) { return this.parseIllust(e) }).bind(this))

                return { comics: comics, next: json.next_url || null }
            },
        }
    ]

    // ============================================================
    //  CATEGORY (stub)
    // ============================================================

    category = {
        title: "Pixiv",
        parts: [],
        enableRankingPage: false,
    }

    categoryComics = {
        load: async (category, param, options, page) => {
            if (category === 'user_illusts') {
                let offset = (page - 1) * 30
                let json = await this.apiGet(
                    this.apiBase + '/v1/user/illusts?filter=for_android&user_id=' + param + '&offset=' + offset)
                let illusts = json.illusts || []
                let comics = illusts.map((function(e) { return this.parseIllust(e) }).bind(this))
                let maxPage = illusts.length < 30 ? page : page + 1
                return { comics: comics, maxPage: maxPage }
            }
            return { comics: [], maxPage: 1 }
        },
    }

    // ============================================================
    //  SEARCH (stub)
    // ============================================================

    search = {
        load: async (keyword, options, page) => {
            return { comics: [], maxPage: 1 }
        },
    }

    // ============================================================
    //  FAVORITES (stub)
    // ============================================================

    favorites = {
        multiFolder: false,

        addOrDelFavorite: async (comicId, folderId, isAdding, favoriteId) => {
            throw 'Login expired'
        },

        loadFolders: async (comicId) => {
            return { folders: {}, favorited: [] }
        },

        loadComics: async (page, folder) => {
            return { comics: [], maxPage: 1 }
        },
    }

    // ============================================================
    //  COMIC
    // ============================================================

    comic = {

        loadInfo: async (id) => {
            let json = await this.apiGet(
                this.apiBase + '/v1/illust/detail?illust_id=' + id)
            let illust = json.illust
            if (!illust) throw 'Illust not found'

            let chapters = {}
            chapters['0'] = illust.title

            let tagsObj = {}
            let contentTags = (illust.tags || []).map(function(t) { return t.translated_name || t.name })
            if (contentTags.length > 0) tagsObj['Tags'] = contentTags
            tagsObj['Artist'] = [illust.user.name + ' |' + illust.user.id]

            return new ComicDetails({
                title: illust.title,
                subtitle: illust.user.name,
                cover: illust.image_urls.medium,
                description: illust.caption || '',
                tags: tagsObj,
                chapters: chapters,
                isFavorite: null,
                url: 'https://www.pixiv.net/artworks/' + illust.id,
                commentCount: illust.total_comments || 0,
                likesCount: illust.total_bookmarks || 0,
                uploadTime: illust.create_date,
                maxPage: illust.page_count || 1
            })
        },

        loadEp: async (comicId, epId) => {
            let json = await this.apiGet(
                this.apiBase + '/v1/illust/detail?illust_id=' + comicId)
            let illust = json.illust
            if (!illust) throw 'Illust not found'

            let images = []
            if (illust.page_count <= 1 || !illust.meta_pages || illust.meta_pages.length === 0) {
                let url = illust.meta_single_page?.original_image_url
                    || illust.image_urls.large
                images.push(url)
            } else {
                for (let i = 0; i < illust.meta_pages.length; i++) {
                    let page = illust.meta_pages[i]
                    images.push(page.image_urls.original || page.image_urls.large)
                }
            }
            return { images: images }
        },

        onImageLoad: (url, comicId, epId) => {
            return {
                headers: {
                    'Referer': 'https://app-api.pixiv.net/',
                    'User-Agent': Pixiv.USER_AGENT
                }
            }
        },

        onThumbnailLoad: (url) => {
            return {
                headers: {
                    'Referer': 'https://app-api.pixiv.net/',
                    'User-Agent': Pixiv.USER_AGENT
                }
            }
        },

        onClickTag: (namespace, tag) => {
            if (namespace === 'Artist') {
                let idx = tag.lastIndexOf('|')
                if (idx !== -1) {
                    return {
                        page: 'category',
                        attributes: {
                            category: 'user_illusts',
                            param: tag.substring(idx + 1).trim()
                        }
                    }
                }
            }
            if (tag && tag.startsWith('artist:')) {
                return {
                    page: 'category',
                    attributes: {
                        category: 'user_illusts',
                        param: tag.substring(7)
                    }
                }
            }
            return {
                page: 'search',
                keyword: tag,
            }
        },

        idMatch: "^\\d+$",
    }

    // ============================================================
    //  ACCOUNT
    //
    //  PKCE flow (Pixiv official App login):
    //    WebView opens app-api.pixiv.net/web/v1/login?code_challenge=...
    //    → server creates PKCE session → redirects to accounts.pixiv.net/login
    //    → user logs in → Pixiv redirects through PKCE start → callback?code=...
    //    → checkStatus captures code → onLoginSuccess exchanges for token
    //
    //  Fallback: localStorage extraction + manual refresh_token
    // ============================================================

    account = {

        loginWithWebview: {
            url: (function() {
                let chars = Pixiv.PKCE_CHARS
                let verifier = ''
                for (let i = 0; i < 128; i++) verifier += chars[randomInt(0, chars.length - 1)]
                Pixiv._pkceVerifier = verifier
                let hash = Convert.sha256(Convert.encodeUtf8(verifier))
                let b64 = Convert.encodeBase64(hash)
                let challenge = ''
                for (let i = 0; i < b64.length; i++) {
                    let c = b64[i]
                    if (c === '+') challenge += '-'
                    else if (c === '/') challenge += '_'
                    else if (c === '=') break
                    else challenge += c
                }
                let pkceStart = 'https://app-api.pixiv.net/web/v1/users/auth/pixiv/start' +
                    '?code_challenge=' + challenge +
                    '&code_challenge_method=S256' +
                    '&client=pixiv-android'
                return 'https://app-api.pixiv.net/web/v1/login' +
                    '?code_challenge=' + challenge +
                    '&code_challenge_method=S256' +
                    '&client=pixiv-android'
            })(),

            checkStatus: (url, title) => {
                console.log('[Pixiv] checkStatus url=' + url)

                // PKCE callback: Pixiv redirects here with auth code after login
                let codeIdx = url.indexOf('code=')
                if (url.indexOf('/auth/pixiv/callback') !== -1 && codeIdx !== -1) {
                    console.log('[Pixiv] checkStatus → PKCE callback, capturing code')
                    let start = codeIdx + 5
                    let end = url.indexOf('&', start)
                    if (end === -1) end = url.length
                    let code = url.substring(start, end)
                    if (code) {
                        this.saveData('_pkce_code', decodeURIComponent(code))
                        console.log('[Pixiv] PKCE code saved')
                        return true
                    }
                }

                return false
            },

            onLoginSuccess: () => {
                console.log('[Pixiv] onLoginSuccess triggered')
                let code = this.loadData('_pkce_code')
                if (!code) {
                    console.log('[Pixiv] WARN: no PKCE code in onLoginSuccess')
                    return
                }
                console.log('[Pixiv] Exchanging PKCE code...')
                this._exchangeAuthCode().then(function(ok) {
                    console.log('[Pixiv] _exchangeAuthCode result=' + ok)
                    if (ok) this._regeneratePkce()
                }.bind(this)).catch(function(e) {
                    console.log('[Pixiv] _exchangeAuthCode error=' + e)
                })
            },
        },

        login: async (account, pwd) => {
            console.log('[Pixiv] login() called, account=' + !!account)

            // 1) Exchange pending PKCE auth code
            let code = this.loadData('_pkce_code')
            if (code) {
                console.log('[Pixiv] login: path 1 - PKCE code exchange')
                let ok = await this._exchangeAuthCode()
                if (ok) return 'ok'
                throw 'Login failed: unable to exchange authorization code'
            }

            // 2) Exchange pending webview token
            let pending = this.loadData('pending_refresh_token')
            if (pending) {
                console.log('[Pixiv] login: path 2 - pending refresh_token exchange')
                let ok = await this._exchangeWebviewToken()
                if (ok) return 'ok'
                throw 'Login failed: unable to exchange webview token'
            }

            // 3) Refresh existing stored token
            if (this.loadData('refresh_token')) {
                console.log('[Pixiv] login: path 3 - refresh existing token')
                try {
                    await this.refreshToken()
                    return 'ok'
                } catch (e) {
                    throw 'Login failed: unable to refresh token'
                }
            }

            // 4) Manual refresh_token via account parameter
            let manual = (account || '').trim()
            if (manual) {
                console.log('[Pixiv] login: path 4 - manual refresh_token')
                this.saveData('refresh_token', manual)
                try {
                    await this.refreshToken()
                    return 'ok'
                } catch (e) {
                    this.deleteData('refresh_token')
                    throw 'Login failed: invalid refresh token'
                }
            }

            console.log('[Pixiv] login: FAILED - no token available')
            throw 'Please login via WebView first, or provide a valid refresh_token'
        },

        logout: () => {
            this.deleteData('access_token')
            this.deleteData('refresh_token')
            this.deleteData('pending_refresh_token')
            this.deleteData('_pkce_code')
            this.deleteData('user_id')
            this.deleteData('user_name')
            this.deleteData('user_account')
            Network.deleteCookies('https://www.pixiv.net')
            Network.deleteCookies('https://accounts.pixiv.net')
        },

        registerWebsite: 'https://www.pixiv.net/signup/'
    }

    // ============================================================
    //  SETTINGS
    // ============================================================

    settings = {
        apiHost: {
            title: "API Host",
            type: "input",
            default: "https://app-api.pixiv.net",
            validator: "^https?://.+"
        }
    }

    // ============================================================
    //  TRANSLATION
    // ============================================================

    translation = {
        'zh_CN': {
            'API Host': 'API 地址',
            'Following': '关注',
        },
        'zh_TW': {
            'API Host': 'API 位址',
            'Following': '關注',
        },
        'en': {}
    }
}
